Post install
infrawatch/functional-tests pull request #23
Opened 2021-02-01 17:55 UTC by lnatapov

2021-03-03 13:14 UTC, paramite requested changes

2021-03-04 14:36 UTC, lnatapov commented on roles/post_install/collectd_query/files/query_collectd_cpu_ceph_bytes.sh
> +curl -k "https://prometheus-operated-service-telemetry.apps.leonidcluster.lab.upshift.rdu2.redhat.com/api/v1/query?" --data-urlencode 'query=collectd_ceph_ceph_bytes {plugin_instance="ceph-osd.0",typ
Thanks,Martin. Will add as ansible parameter

2021-03-04 15:18 UTC, leifmadsen commented on roles/post_install/collectd_query/files/query_collectd_cpu_ceph_bytes.sh
> +curl -k "https://prometheus-operated-service-telemetry.apps.leonidcluster.lab.upshift.rdu2.redhat.com/api/v1/query?" --data-urlencode 'query=collectd_ceph_ceph_bytes {plugin_instance="ceph-osd.0",typ
This is the kind of functional testing we might be able to start running against our downstream testing too, and not just in the QE lab. At least at some point :)

If this was a parameter then we could point this at any STF instance.

2021-04-25 21:18 UTC, closed without merging

2021-04-25 21:19 UTC, lnatapov commented
A new pull request was created